import fs from "fs"
import path from "path"

const ICONS_DIR = path.resolve("src/components/icons/doomscrll-icons")
const INDEX_FILE = path.resolve("src/components/icons/doomscrll-icons/index.ts")

function generateIconsMap() {
	const files = fs.readdirSync(ICONS_DIR).filter((file) => /^icon-.*\.svelte$/.test(file))

	if (files.length === 0) {
		console.warn(`generateIconsMap: Couldn't find any inline-icon components in ${ICONS_DIR}.`)
		return
	}

	let imports = ""
	let mapEntries = ""
	const names: Array<string> = []

	files.forEach((file) => {
		const baseName = file.replace(/^icon-/, "").replace(/\.svelte$/, "")
		const iconName = baseName
			.split("-")
			.map((word) => word.charAt(0).toUpperCase() + word.slice(1))
			.join("")

		imports += `import ${iconName} from "./${file}"\n`
		mapEntries += `\t${iconName},\n`
		names.push(`"${iconName}"`)
	})

	const fileContent = `// AUTO-GENERATED BY \`generate-icons-map.ts\`
// Run the generator script to update this file.

${imports}
const ICONS = {
${mapEntries}} as const

export type DoomscrllIcon = keyof typeof ICONS

export function getDoomscrllIcon(name: DoomscrllIcon) {
  return ICONS[name]
}
  `

	fs.writeFileSync(INDEX_FILE, fileContent, "utf-8")
	console.log(`generateIconsMap: Generated ${files.length} icons in "/components/icons/doomscrll-icons/index.ts"`)
}

generateIconsMap()
