import type { Platform } from "models/platform"

export const PLATFORMS_GAME = [
	"Apple App Store",
	"Epic Games Store",
	"GOG",
	"Google Play Store",
	"itch.io",
	"Nintendo Switch",
	"PlayStation",
	"Steam",
	"Xbox",
] as const

export const PLATFORMS_SOCIAL = [
	"Bluesky",
	"Discord",
	"Instagram",
	"Kick",
	"Kickstarter",
	"Ko-fi",
	"Mailing List",
	"Website",
	"Mastodon",
	"Matrix",
	"Patreon",
	"Reddit",
	"TikTok",
	"Twitch",
	"X",
	"YouTube",
] as const

export const PLATFORMS: { [key in Platform]: string } = {
	"Apple App Store": "app-store",
	"Epic Games Store": "egs",
	GOG: "gog",
	"Google Play Store": "play-store",
	"itch.io": "itch-io",
	"Nintendo Switch": "switch",
	PlayStation: "ps",
	Steam: "steam",
	Xbox: "xbox",
	Bluesky: "bsky",
	Discord: "discord",
	Instagram: "ig",
	Kick: "kick",
	Kickstarter: "kickstarter",
	"Ko-fi": "ko-fi",
	"Mailing List": "mail-list",
	Website: "web",
	Mastodon: "mastodon",
	Matrix: "matrix",
	Patreon: "patreon",
	Reddit: "reddit",
	TikTok: "tiktok",
	Twitch: "twitch",
	X: "twitter",
	YouTube: "youtube",
}
