import type Category from "models/category"
import type ProjectTag from "models/project-tag"

const TAGS: { [key in Category]: ProjectTag[] } = {
	"Video Games": [
		// Core Genres
		"#action",
		"#adventure",
		"#arcade",
		"#casual",
		"#fighting",
		"#puzzle",
		"#racing",
		"#rpg",
		"#simulation",
		"#sports",
		"#strategy",
		"#visual-novel",

		// Sub-Genres & Deep Mechanics
		"#4x",
		"#action-rpg",
		"#automation",
		"#beat-em-up",
		"#bullet-heaven",
		"#cards",
		"#city-builder",
		"#crpg",
		"#deckbuilder",
		"#dungeon-crawler",
		"#exploration",
		"#god-sim",
		"#horde-survival",
		"#idle",
		"#jrpg",
		"#management",
		"#mecha",
		"#metroidvania",
		"#platformer",
		"#point-and-click",
		"#rhythm",
		"#roguelike",
		"#rts",
		"#sandbox",
		"#shooter",
		"#souls-like",
		"#stealth",
		"#tactical",
		"#tower-defense",

		// Survival, Crafting & Activities
		"#base-building",
		"#building",
		"#cooking",
		"#creature-collector",
		"#extraction",
		"#farming",
		"#fishing",
		"#golf",
		"#mining",
		"#survival",
		"#survival-craft",

		// Narrative, Horror & Group Play
		"#choices-matter",
		"#co-op",
		"#horror",
		"#interactive-fiction",
		"#party",
		"#psychological-horror",
		"#social-deduction",
		"#story-rich",

		// Vibes & Specific Audiences
		"#cozy",
		"#life-sim",
		"#nsfw",
		"#wholesome",

		// Themes & Settings
		"#anime",
		"#comedy",
		"#cyberpunk",
		"#dark-fantasy",
		"#detective",
		"#fantasy",
		"#historical",
		"#lovecraftian",
		"#medieval",
		"#military",
		"#mystery",
		"#mythology",
		"#pirates",
		"#post-apocalyptic",
		"#sci-fi",
		"#space",
		"#steampunk",
		"#vampires",
		"#western",
		"#zombies",

		// Hardware
		"#vr",
	],
	Tabletop: [
		// Core Genres & Game Types
		"#board-game",
		"#card-game",
		"#co-op",
		"#dice-game",
		"#family",
		"#legacy",
		"#party",
		"#social-deduction",
		"#strategy",
		"#wargame",

		//Formats & Deliverables
		"#adventure",
		"#business-card",
		"#campaign",
		"#miniatures",
		"#one-page",
		"#print-and-play",
		"#supplement",
		"#zine",

		//Player Count & Playstyle
		"#duet",
		"#gm-less",
		"#journaling",
		"#one-shot",
		"#solo",
		"#two-player",

		// RPG Systems & Philosophies
		"#dnd",
		"#fitd",
		"#hexcrawl",
		"#osr",
		"#pbta",
		"#system-neutral",

		// Mechanics & Engines
		"#area-control",
		"#deckbuilder",
		"#diceless",
		"#dungeon-crawler",
		"#engine-builder",
		"#oracle",
		"#push-your-luck",
		"#roll-and-write",
		"#tile-placement",
		"#trick-taking",
		"#worker-placement",

		// Themes & Settings
		"#anime",
		"#comedy",
		"#cyberpunk",
		"#dark-fantasy",
		"#detective",
		"#fantasy",
		"#historical",
		"#lovecraftian",
		"#medieval",
		"#mystery",
		"#mythology",
		"#pirates",
		"#post-apocalyptic",
		"#sci-fi",
		"#space",
		"#steampunk",
		"#western",
		"#zombies",
	],
	"Software & Tools": [
		// Creative & Asset Creation
		"#3d-modeling",
		"#animation",
		"#audio-production",
		"#drawing",
		"#illustration",
		"#low-poly",
		"#photo-editing",
		"#pixel-art",
		"#video-editing",
		"#voxel",

		// Game Development & Design
		"#game-engine",
		"#level-editor",
		"#plugin",
		"#ui-design",
		"#wireframing",

		// Development & Engineering
		"#api",
		"#cloud",
		"#cms",
		"#code-editor",
		"#database",
		"#framework",
		"#git",
		"#static-site-generator",
		"#terminal",
		"#testing",
		"#website-builder",

		// Productivity & Workflow
		"#calendar",
		"#crm",
		"#file-sharing",
		"#note-taking",
		"#productivity",
		"#project-management",
		"#seo",
		"#spreadsheets",
		"#time-tracking",

		// AI & Automation
		"#ai",
		"#automation",
		"#chatbot",
		"#llm",
		"#low-code",
		"#machine-learning",
		"#no-code",
		"#text-to-speech",

		// General Utilities
		"#crypto",
		"#utility",
		"#web3",
	],
	"Digital Assets": [
		//  Top-Level Asset Types
		"#3d-print",
		"#diy",
		"#extension",
		"#game-asset",
		"#plugin",
		"#template",

		//  2D Art & Surfaces
		"#2d",
		"#brushes",
		"#decals",
		"#materials",
		"#pixel-art",
		"#sprites",
		"#textures",
		"#tileset",

		//  3D Models & Animation
		"#3d",
		"#animations",
		"#characters",
		"#environments",
		"#hdri",
		"#low-poly",
		"#props",
		"#rigged",
		"#vegetation",
		"#vehicles",

		//  VFX & Technical Art
		"#particles",
		"#post-processing",
		"#shaders",
		"#texture",
		"#mod",
		"#vfx",

		//  Interface & Typography
		"#fonts",
		"#gui",
		"#icons",
		"#overlays",
		"#ui",

		//  Game Systems & Code
		"#addons",
		"#game-system",
		"#scripts",

		//  3D Printing & Maker
		"#cosplay",
		"#functional",
		"#miniatures",
		"#obj",
		"#sculpture",
		"#stl",
		"#terrain",
		"#toys",

		//  Audio Assets
		"#ambient",
		"#music",
		"#sound-effects",
		"#voice-lines",

		//  Tool & Engine Compatibility
		"#blender",
		"#figma",
		"#godot",
		"#photoshop",
		"#procreate",
		"#unity",
		"#unreal",
		"#notion",
		"#canva",
		"#framer",
		"#webflow",
		"#wordpress",
		"#shopify",
		"#vrchat",
		"#minecraft",
		"#roblox",
		"#vtuber",
	],
	Publishing: [
		// Formats & Deliverables
		"#article",
		"#audiobook",
		"#comic",
		"#essay",
		"#graphic-novel",
		"#manga",
		"#newsletter",
		"#novel",
		"#poetry",
		"#serial",
		"#short-story",
		"#webcomic",
		"#zine",

		// Fiction Genres & Tropes
		"#action",
		"#bl",
		"#comedy",
		"#dark-romance",
		"#drama",
		"#dystopian",
		"#fantasy",
		"#gl",
		"#heartwarming",
		"#historical",
		"#horror",
		"#isekai",
		"#litrpg",
		"#mystery",
		"#progression-fantasy",
		"#romance",
		"#sci-fi",
		"#slice-of-life",
		"#superhero",
		"#supernatural",
		"#thriller",
		"#urban-fantasy",
		"#young-adult",

		// Non-Fiction & Topics
		"#art",
		"#biography",
		"#business",
		"#culture",
		"#economics",
		"#finance",
		"#food",
		"#health",
		"#history",
		"#memoir",
		"#music",
		"#philosophy",
		"#politics",
		"#productivity",
		"#science",
		"#self-help",
		"#sports",
		"#technology",
		"#travel",
	],
	Audio: [
		// Core Genres (Music & Spoken)
		"#alternative",
		"#classical",
		"#comedy",
		"#country",
		"#dance",
		"#educational",
		"#electronic",
		"#folk",
		"#hip-hop",
		"#jazz",
		"#metal",
		"#news",
		"#pop",
		"#reggae",
		"#rnb",
		"#rock",
		"#true-crime",
		"#world",

		// Sub-Genres & Styles
		"#afrobeat",
		"#boom-bap",
		"#drill",
		"#experimental",
		"#house",
		"#indie",
		"#lofi",
		"#punk",
		"#singer-songwriter",
		"#synthwave",
		"#techno",
		"#trap",

		// Formats & Deliverables
		"#acapella",
		"#audio-drama",
		"#beat",
		"#instrumental",
		"#interview",
		"#podcast",
		"#sample",
		"#soundtrack",
		"#storytelling",
		"#type-beat",
		"#vocal",

		// Moods & Identifiers
		"#acoustic",
		"#ambient",
		"#chill",
		"#dark",
		"#hard",
		"#sad",
		"#soulful",
		"#upbeat",

		// Primary Instruments
		"#808",
		"#guitar",
		"#piano",
		"#synthesizer",
	],
	Video: [
		// Formats & Deliverables
		"#asmr",
		"#case-study",
		"#course",
		"#deep-dive",
		"#demo",
		"#documentary",
		"#experimental",
		"#feature-film",
		"#gameplay",
		"#highlights",
		"#interview",
		"#let-s-play",
		"#music-video",
		"#podcast",
		"#reaction",
		"#review",
		"#short-film",
		"#showcase",
		"#speedrun",
		"#stream-vod",
		"#tutorial",
		"#unboxing",
		"#video-essay",
		"#vlog",
		"#walkthrough",

		// Styles & Techniques
		"#2d-animation",
		"#3d-animation",
		"#cinematic",
		"#live-action",
		"#motion-graphics",
		"#stop-motion",
		"#vfx",

		// Topics & Niches (Non-Fiction)
		"#art",
		"#business",
		"#coding",
		"#commentary",
		"#cooking",
		"#diy",
		"#education",
		"#finance",
		"#fitness",
		"#gaming",
		"#history",
		"#lifestyle",
		"#music",
		"#myth-busting",
		"#politics",
		"#science",
		"#science-experiment",
		"#tech-review",
		"#technology",
		"#travel",
		"#true-crime",

		// Genres (Narrative Fiction)
		"#action",
		"#comedy",
		"#drama",
		"#horror",
		"#sci-fi",
		"#thriller",
	],
	Goods: [
		// Top-Level Categories
		"#accessories",
		"#apparel",
		"#art",
		"#beauty",
		"#clothing",
		"#collectibles",
		"#home-decor",
		"#stationery",
		"#toys",

		// Apparel & Clothing
		"#activewear",
		"#costume",
		"#dress",
		"#hoodie",
		"#jacket",
		"#pants",
		"#shirt",
		"#sweater",
		"#swimwear",
		"#t-shirt",

		// Accessories & Wearables
		"#bag",
		"#belt",
		"#enamel-pin",
		"#glasses",
		"#hat",
		"#jewelry",
		"#keychain",
		"#patch",
		"#purse",
		"#scarf",
		"#wallet",

		// Art & Collectibles
		"#art-print",
		"#canvas",
		"#figurine",
		"#original-art",
		"#painting",
		"#poster",
		"#sculpture",
		"#trading-card",

		// Home & Living
		"#blanket",
		"#candle",
		"#ceramic",
		"#decor",
		"#furniture",
		"#glassware",
		"#lighting",
		"#mug",
		"#pillow",
		"#rug",
		"#tapestry",

		// Stationery & Paper Goods
		"#bookmark",
		"#calendar",
		"#greeting-card",
		"#journal",
		"#notebook",
		"#planner",
		"#sticker",
		"#washi-tape",

		// Tech & Desk Accessories
		"#desk-mat",
		"#keycap",
		"#mousepad",
		"#phone-case",

		// Toys, Plush & Hobbies
		"#action-figure",
		"#board-game",
		"#diorama",
		"#doll",
		"#miniature",
		"#model-kit",
		"#plushie",
		"#puzzle",
		"#toy",

		// Body & Beauty
		"#bath-bomb",
		"#cosmetics",
		"#fragrance",
		"#skincare",
		"#soap",
	],
	Food: [
		// Top-Level Categories
		"#beverages",
		"#dietary",
		"#pantry",
		"#prepared-meals",
		"#snacks-and-sweets",

		// Pantry & Artisan Goods
		"#condiment",
		"#honey",
		"#hot-sauce",
		"#jam",
		"#nut-butter",
		"#olive-oil",
		"#sauce",
		"#spice-blend",
		"#spread",
		"#vinegar",

		// Snacks & Sweets
		"#baked-goods",
		"#candy",
		"#chocolate",
		"#cookie",
		"#dried-fruit",
		"#jerky",
		"#nuts",
		"#pastry",

		// Beverages
		"#coffee",
		"#energy-drink",
		"#juice",
		"#kombucha",
		"#matcha",
		"#soda",
		"#tea",

		// Prepared & Meal Formats
		"#local-delivery",
		"#local-pickup",
		"#meal-kit",
		"#prepared-meal",
		"#subscription-box",

		// Dietary & Health Needs
		"#allergen-free",
		"#dairy-free",
		"#gluten-free",
		"#keto",
		"#kosher",
		"#low-sugar",
		"#nut-free",
		"#organic",
		"#plant-based",
		"#vegan",
		"#vegetarian",
	],
	Local: [
		// Top-Level Categories
		"#artisan-food",
		"#creative-services",
		"#indie-retail",
		"#studios-and-spaces",
		"#wellness-and-body-art",

		// Artisan Food & Dining (Indie/Craft)
		"#bakery",
		"#brewery",
		"#cafe",
		"#catering",
		"#coffee-roastery",
		"#food-truck",
		"#micro-distillery",
		"#pop-up-kitchen",

		// Indie Retail & Boutiques
		"#art-gallery",
		"#book-store",
		"#boutique",
		"#comic-shop",
		"#craft-supply",
		"#florist",
		"#plant-shop",
		"#record-store",
		"#vintage-shop",

		// Creative Services & Freelancers
		"#audio-engineer",
		"#event-planner",
		"#graphic-designer",
		"#music-teacher",
		"#photographer",
		"#print-shop",
		"#videographer",
		"#web-developer",

		// Studios, Spaces & Workshops
		"#art-studio",
		"#coworking-space",
		"#dance-studio",
		"#makerspace",
		"#martial-arts-dojo",
		"#music-studio",
		"#pottery-studio",
		"#yoga-studio",

		// Wellness, Personal Care & Body Art
		"#barber",
		"#hair-stylist",
		"#makeup-artist",
		"#massage-therapist",
		"#nail-artist",
		"#piercing-studio",
		"#tattoo-studio",
	],
	Internal_Socials: [],
	Internal_Crowdfunding: [],
} as const

export default TAGS
