// AUTO-GENERATED BY `generate-icons-map.ts`
// Run the generator script to update this file.

import ArrowBack from "./icon-arrow-back.svelte"
import ArrowDropdown from "./icon-arrow-dropdown.svelte"
import ArrowExternal from "./icon-arrow-external.svelte"
import ArrowForward from "./icon-arrow-forward.svelte"
import AvatarAnon from "./icon-avatar-anon.svelte"
import AvatarSigned from "./icon-avatar-signed.svelte"
import Cancel from "./icon-cancel.svelte"
import DoomeyeClosed from "./icon-doomeye-closed.svelte"
import Doomeye from "./icon-doomeye.svelte"
import Help from "./icon-help.svelte"
import Link from "./icon-link.svelte"
import Mail from "./icon-mail.svelte"
import Purchase from "./icon-purchase.svelte"
import Remove from "./icon-remove.svelte"
import Settings from "./icon-settings.svelte"
import Starmark from "./icon-starmark.svelte"
import Upload from "./icon-upload.svelte"

const ICONS = {
	ArrowBack,
	ArrowDropdown,
	ArrowExternal,
	ArrowForward,
	AvatarAnon,
	AvatarSigned,
	Cancel,
	DoomeyeClosed,
	Doomeye,
	Help,
	Link,
	Mail,
	Purchase,
	Remove,
	Settings,
	Starmark,
	Upload,
} as const

export type DoomscrllIcon = keyof typeof ICONS

export function getDoomscrllIcon(name: DoomscrllIcon) {
	return ICONS[name]
}
